# Generated by Django 3.0.3 on 2020-02-29 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StationsQuestinon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TextElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionrequest.Question', verbose_name='Вопросы')),
                ('station_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionrequest.StationsQuestinon', verbose_name='Название станции')),
            ],
        ),
        migrations.AddField(
            model_name='stationsquestinon',
            name='questions',
            field=models.ManyToManyField(through='questionrequest.TextElem', to='questionrequest.Question'),
        ),
    ]
