# Generated by Django 2.2.7 on 2020-03-03 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionrequest', '0005_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textelem',
            name='questions_name',
        ),
        migrations.RemoveField(
            model_name='textelem',
            name='station_name',
        ),
        migrations.RemoveField(
            model_name='textelem',
            name='who',
        ),
        migrations.AddField(
            model_name='question',
            name='station',
            field=models.CharField(default='', max_length=200, verbose_name='Название станции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='who',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Для кого вопросы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Текст вопроса'),
        ),
        migrations.DeleteModel(
            name='StationsQuestinon',
        ),
        migrations.DeleteModel(
            name='TextElem',
        ),
    ]
